services:
  mongodb:
    image: mongo:latest
    container_name: breakoutzone-database
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:

